<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.smartlogic.oeclient</groupId>
	<artifactId>Semaphore-OE-Client</artifactId>

	<name>Semaphore-OE-Client</name>
	<description>Ontology Editor API</description>

	<packaging>jar</packaging>

	<parent>
		<groupId>com.smartlogic</groupId>
		<artifactId>Semaphore-Java-APIs</artifactId>
		<version>5.10.2-SNAPSHOT</version>
	</parent>


	<dependencies>
		<dependency>
			<groupId>org.apache.jena</groupId>
			<artifactId>apache-jena-libs</artifactId>
			<version>${jena.version}</version>
			<type>pom</type>
		</dependency>
		<dependency>
			<groupId>com.smartlogic.cloud</groupId>
			<artifactId>Semaphore-Cloud-Client</artifactId>
			<version>5.10.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpmime</artifactId>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<profiles>
		<profile>
			<id>integration</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>build-helper-maven-plugin</artifactId>
						<version>3.6.0</version>
						<executions>
							<execution>
								<id>add-integration-test-sources</id>
								<phase>generate-test-sources</phase>
								<goals>
									<goal>add-test-source</goal>
								</goals>
								<configuration>
									<sources>
										<source>src/integration-test/java</source>
									</sources>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-failsafe-plugin</artifactId>
						<version>3.5.3</version>
						<dependencies>
							<dependency>
								<groupId>junit</groupId>
								<artifactId>junit</artifactId>
								<version>${junit.version}</version>
							</dependency>
						</dependencies>
						<executions>
							<execution>
								<goals>
									<goal>integration-test</goal>
									<goal>verify</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
			<dependencies>
				<dependency>
					<groupId>junit</groupId>
					<artifactId>junit</artifactId>
					<version>${junit.version}</version>
					<scope>test</scope>
				</dependency>
			</dependencies>
		</profile>
	</profiles>

</project>